import django1   from "../../assests/images/django/django1.png"
import django100 from "../../assests/images/django/django100.png"
import django101 from "../../assests/images/django/django101.png"
import django102 from "../../assests/images/django/django102.png"
import django103 from "../../assests/images/django/django103.png"
import django104 from "../../assests/images/django/django104.png"
import django105 from "../../assests/images/django/django105.png"
import django106 from "../../assests/images/django/django106.png"
import django107 from "../../assests/images/django/django107.png"
import django108 from "../../assests/images/django/django108.png"
import django109 from "../../assests/images/django/django109.png"
import django110 from "../../assests/images/django/django110.png"
import django111 from "../../assests/images/django/django111.png"
import django112 from "../../assests/images/django/django112.png"
import django113 from "../../assests/images/django/django113.png"
import django114 from "../../assests/images/django/django114.png"
import django115 from "../../assests/images/django/django115.png"
import django116 from "../../assests/images/django/django116.png"
import django117 from "../../assests/images/django/django117.png"
import django118 from "../../assests/images/django/django118.png"
import django119 from "../../assests/images/django/django119.png"
import django12  from "../../assests/images/django/django12.png"
import django120 from "../../assests/images/django/django120.png"
import django121 from "../../assests/images/django/django121.png"
import django122 from "../../assests/images/django/django122.png"
import django123 from "../../assests/images/django/django123.png"
import django124 from "../../assests/images/django/django124.png"
import django125 from "../../assests/images/django/django125.png"
import django126 from "../../assests/images/django/django126.png"
import django127 from "../../assests/images/django/django127.png"
import django128 from "../../assests/images/django/django128.png"
import django129 from "../../assests/images/django/django129.png"
import django130 from "../../assests/images/django/django130.png"
import django131 from "../../assests/images/django/django131.png"
import django132 from "../../assests/images/django/django132.png"
import django133 from "../../assests/images/django/django133.png"
import django134 from "../../assests/images/django/django134.png"
import django135 from "../../assests/images/django/django135.png"
import django141 from "../../assests/images/django/django141.png"
import django142 from "../../assests/images/django/django142.png"
import django143 from "../../assests/images/django/django143.png"
import django148 from "../../assests/images/django/django148.png"
import django149 from "../../assests/images/django/django149.png"
import django150 from "../../assests/images/django/django150.png"
import django151 from "../../assests/images/django/django151.png"
import django152 from "../../assests/images/django/django152.png"
import django158 from "../../assests/images/django/django158.png"
import django159 from "../../assests/images/django/django159.png"
import django16  from "../../assests/images/django/django16.png"
import django160 from "../../assests/images/django/django160.png"
import django161 from "../../assests/images/django/django161.png"
import django162 from "../../assests/images/django/django162.png"
import django163 from "../../assests/images/django/django163.png"
import django166 from "../../assests/images/django/django166.png"
import django172 from "../../assests/images/django/django172.png"
import django174 from "../../assests/images/django/django174.png"
import django176 from "../../assests/images/django/django176.png"
import django177 from "../../assests/images/django/django177.png"
import django178 from "../../assests/images/django/django178.png"
import django179 from "../../assests/images/django/django179.png"
import django18  from "../../assests/images/django/django18.png"
import django180 from "../../assests/images/django/django180.png"
import django181 from "../../assests/images/django/django181.png"
import django182 from "../../assests/images/django/django182.png"
import django183 from "../../assests/images/django/django183.png"
import django184 from "../../assests/images/django/django184.png"
import django185 from "../../assests/images/django/django185.png"
import django186 from "../../assests/images/django/django186.png"
import django188 from "../../assests/images/django/django188.png"
import django189 from "../../assests/images/django/django189.png"
import django19  from "../../assests/images/django/django19.png"
import django190 from "../../assests/images/django/django190.png"
import django194 from "../../assests/images/django/django194.png"
import django2   from "../../assests/images/django/django2.png"
import django202 from "../../assests/images/django/django202.png"
import django203 from "../../assests/images/django/django203.png"
import django204 from "../../assests/images/django/django204.png"
import django205 from "../../assests/images/django/django205.png"
import django206 from "../../assests/images/django/django206.png"
import django207 from "../../assests/images/django/django207.png"
import django208 from "../../assests/images/django/django208.png"
import django209 from "../../assests/images/django/django209.png"
import django210 from "../../assests/images/django/django210.png"
import django211 from "../../assests/images/django/django211.png"
import django212 from "../../assests/images/django/django212.png"
import django213 from "../../assests/images/django/django213.png"
import django214 from "../../assests/images/django/django214.png"
import django215 from "../../assests/images/django/django215.png"
import django216 from "../../assests/images/django/django216.png"
import django217 from "../../assests/images/django/django217.png"
import django218 from "../../assests/images/django/django218.png"
import django219 from "../../assests/images/django/django219.png"
import django220 from "../../assests/images/django/django220.png"
import django221 from "../../assests/images/django/django221.png"
import django222 from "../../assests/images/django/django222.png"
import django223 from "../../assests/images/django/django223.png"
import django224 from "../../assests/images/django/django224.png"
import django225 from "../../assests/images/django/django225.png"
import django226 from "../../assests/images/django/django226.png"
import django227 from "../../assests/images/django/django227.png"
import django228 from "../../assests/images/django/django228.png"
import django229 from "../../assests/images/django/django229.png"
import django23  from "../../assests/images/django/django23.png"
import django230 from "../../assests/images/django/django230.png"
import django231 from "../../assests/images/django/django231.png"
import django232 from "../../assests/images/django/django232.png"
import django233 from "../../assests/images/django/django233.png"
import django234 from "../../assests/images/django/django234.png"
import django235 from "../../assests/images/django/django235.png"
import django236 from "../../assests/images/django/django236.png"
import django237 from "../../assests/images/django/django237.png"
import django238 from "../../assests/images/django/django238.png"
import django239 from "../../assests/images/django/django239.png"
import django24  from "../../assests/images/django/django24.png"
import django240 from "../../assests/images/django/django240.png"
import django241 from "../../assests/images/django/django241.png"
import django242 from "../../assests/images/django/django242.png"
import django243 from "../../assests/images/django/django243.png"
import django244 from "../../assests/images/django/django244.png"
import django245 from "../../assests/images/django/django245.png"
import django246 from "../../assests/images/django/django246.png"
import django247 from "../../assests/images/django/django247.png"
import django248 from "../../assests/images/django/django248.png"
import django25  from "../../assests/images/django/django25.png"
import django26  from "../../assests/images/django/django26.png"
import django27  from "../../assests/images/django/django27.png"
import django28  from "../../assests/images/django/django28.png"
import django29  from "../../assests/images/django/django29.png"
import django3   from "../../assests/images/django/django3.png"
import django30  from "../../assests/images/django/django30.png"
import django31  from "../../assests/images/django/django31.png"
import django32  from "../../assests/images/django/django32.png"
import django33  from "../../assests/images/django/django33.png"
import django39  from "../../assests/images/django/django39.png"
import django4   from "../../assests/images/django/django4.png"
import django40  from "../../assests/images/django/django40.png"
import django41  from "../../assests/images/django/django41.png"
import django42  from "../../assests/images/django/django42.png"
import django43  from "../../assests/images/django/django43.png"
import django44  from "../../assests/images/django/django44.png"
import django45  from "../../assests/images/django/django45.png"
import django46  from "../../assests/images/django/django46.png"
import django47  from "../../assests/images/django/django47.png"
import django48  from "../../assests/images/django/django48.png"
import django49  from "../../assests/images/django/django49.png"
import django50  from "../../assests/images/django/django50.png"
import django51  from "../../assests/images/django/django51.png"
import django52  from "../../assests/images/django/django52.png"
import django53  from "../../assests/images/django/django53.png"
import django54  from "../../assests/images/django/django54.png"
import django55  from "../../assests/images/django/django55.png"
import django56  from "../../assests/images/django/django56.png"
import django57  from "../../assests/images/django/django57.png"
import django58  from "../../assests/images/django/django58.png"
import django59  from "../../assests/images/django/django59.png"
import django60  from "../../assests/images/django/django60.png"
import django61  from "../../assests/images/django/django61.png"
import django62  from "../../assests/images/django/django62.png"
import django63  from "../../assests/images/django/django63.png"
import django64  from "../../assests/images/django/django64.png"
import django65  from "../../assests/images/django/django65.png"
import django67  from "../../assests/images/django/django67.png"
import django68  from "../../assests/images/django/django68.png"
import django69  from "../../assests/images/django/django69.png"
import django70  from "../../assests/images/django/django70.png"
import django71  from "../../assests/images/django/django71.png"
import django72  from "../../assests/images/django/django72.png"
import django73  from "../../assests/images/django/django73.png"
import django74  from "../../assests/images/django/django74.png"
import django75  from "../../assests/images/django/django75.png"
import django76  from "../../assests/images/django/django76.png"
import django77  from "../../assests/images/django/django77.png"
import django78  from "../../assests/images/django/django78.png"
import django79  from "../../assests/images/django/django79.png"
import django80  from "../../assests/images/django/django80.png"
import django81  from "../../assests/images/django/django81.png"
import django82  from "../../assests/images/django/django82.png"
import django83  from "../../assests/images/django/django83.png"
import django84  from "../../assests/images/django/django84.png"
import django85  from "../../assests/images/django/django85.png"
import django86  from "../../assests/images/django/django86.png"
import django87  from "../../assests/images/django/django87.png"
import django88  from "../../assests/images/django/django88.png"
import django89  from "../../assests/images/django/django89.png"
import django9   from "../../assests/images/django/django9.png"
import django90  from "../../assests/images/django/django90.png"
import django91  from "../../assests/images/django/django91.png"
import django92  from "../../assests/images/django/django92.png"
import django93  from "../../assests/images/django/django93.png"
import django94  from "../../assests/images/django/django94.png"
import django95  from "../../assests/images/django/django95.png"
import django96  from "../../assests/images/django/django96.png"
import django97  from "../../assests/images/django/django97.png"
import django98  from "../../assests/images/django/django98.png"
import django99  from "../../assests/images/django/django99.png"
import django5  from "../../assests/images/django/django5.png"
import django5_5  from "../../assests/images/django/django5_5.png"
import django_path from "../../assests/images/django/django_path.png"


const images = {  
    django1,django100,django101,django102,django103,
    django104,django105,django106,django107,django108,
    django109,django110,django111,django112,django113,
    django114,django115,django116,django117,django118,
    django119,django12,django120,django121,django122,
    django123,django124,django125,django126,django127,
    django128,django129,django130,django131,django132,
    django133,django134,django135,django141,django142,
    django143,
    django148,django149,django150,django151,django152,
    django158,django159,django16,django160,django161,
    django162,django163,django166,django172,django174,
    django176,django177,django178,django179,django18,
    django180,django181,django182,django183,django184,
    django185,django186,django188,django189,django19,
    django190,django194,django2,django202,django203,
    django204,django205,django206,django207,django208,
    django209,django210,django211,django212,django213,
    django214,django215,django216,django217,django218,
    django219,django220,django221,django222,django223,
    django224,django225,django226,django227,django228,
    django229,django23,django230,django231,django232,
    django233,django234,django235,django236,django237,
    django238,django239,django24,django240,django241,
    django242,django243,django244,django245,django246,
    django247,django248,django25,django26,django27,
    django28,django29,django3,django30,django31,
    django32,django33,django39,django4,django40,
    django41,django42,django43,django44,django45,
    django46,django47,django48,django49,django50,
    django51,django52,django53,django54,django55,
    django56,django57,django58,django59,django60,django61,
    django62,django63,django64,django65, django67,django68,
    django69,django70,django71,django72,django73,django74,
    django75,django76,django77,django78,django79,django80,
    django81,django82,django83,django84,django85,django86,
    django87,django88,django89,django9,django90,django91,
    django92,django93,django94,django95,django96,django97,
    django98,django99,django_path,django5,django5_5,
}

export default images ;