import controller_r from "../../assests/images/laravel/controller-r.png"
import index from "../../assests/images/laravel/index.png"
import Laravel0 from "../../assests/images/laravel/Laravel0.png"
import laravel0_env from "../../assests/images/laravel/laravel0_env.png"
import laravel0_env2 from "../../assests/images/laravel/laravel0_env2.png"
import laravel0_env3 from "../../assests/images/laravel/laravel0_env3.png"
import laravel0_layoute from "../../assests/images/laravel/laravel0_layoute.png"
import laravel0_model1 from "../../assests/images/laravel/laravel0_model1.png"
import laravel0_model2 from "../../assests/images/laravel/laravel0_model2.png"
import laravel0_result from "../../assests/images/laravel/laravel0_result.png"
import laravel0_result2 from "../../assests/images/laravel/laravel0_result2.png"
import laravel0_show from "../../assests/images/laravel/laravel0_show.png"
import laravel1 from "../../assests/images/laravel/laravel1.png"
import laravel10 from "../../assests/images/laravel/laravel10.png"
import laravel11 from "../../assests/images/laravel/laravel11.png"
import laravel12 from "../../assests/images/laravel/laravel12.png"
import laravel13 from "../../assests/images/laravel/laravel13.png"
import laravel14 from "../../assests/images/laravel/laravel14.png"
import laravel15 from "../../assests/images/laravel/laravel15.png"
import laravel16 from "../../assests/images/laravel/laravel16.png"
import laravel17 from "../../assests/images/laravel/laravel17.png"
import laravel18 from "../../assests/images/laravel/laravel18.png"
import laravel19 from "../../assests/images/laravel/laravel19.png"
import laravel2 from "../../assests/images/laravel/laravel2.png"
import laravel20 from "../../assests/images/laravel/laravel20.png"
import laravel21 from "../../assests/images/laravel/laravel21.png"
import laravel22 from "../../assests/images/laravel/laravel22.png"
import laravel23 from "../../assests/images/laravel/laravel23.png"
import laravel24 from "../../assests/images/laravel/laravel24.png"
import laravel25 from "../../assests/images/laravel/laravel25.png"
import laravel26 from "../../assests/images/laravel/laravel26.png"
import laravel27 from "../../assests/images/laravel/laravel27.png"
import laravel28 from "../../assests/images/laravel/laravel28.png"
import laravel29 from "../../assests/images/laravel/laravel29.png"
import laravel3 from "../../assests/images/laravel/laravel3.png"
import laravel30 from "../../assests/images/laravel/laravel30.png"
import laravel31 from "../../assests/images/laravel/laravel31.png"
import laravel32 from "../../assests/images/laravel/laravel32.png"
import laravel33 from "../../assests/images/laravel/laravel33.png"
import laravel34 from "../../assests/images/laravel/laravel34.png"
import laravel35 from "../../assests/images/laravel/laravel35.png"
import laravel36 from "../../assests/images/laravel/laravel36.png"
import laravel37 from "../../assests/images/laravel/laravel37.png"
import laravel38 from "../../assests/images/laravel/laravel38.png"
import laravel39 from "../../assests/images/laravel/laravel39.png"
import laravel4 from "../../assests/images/laravel/laravel4.png"
import laravel40 from "../../assests/images/laravel/laravel40.png"
import laravel41 from "../../assests/images/laravel/laravel41.png"
import laravel42 from "../../assests/images/laravel/laravel42.png"
import laravel43 from "../../assests/images/laravel/laravel43.png"
import laravel44 from "../../assests/images/laravel/laravel44.png"
import laravel45 from "../../assests/images/laravel/laravel45.png"
import laravel46 from "../../assests/images/laravel/laravel46.png"
import laravel47 from "../../assests/images/laravel/laravel47.png"
import laravel48 from "../../assests/images/laravel/laravel48.png"
import laravel49 from "../../assests/images/laravel/laravel49.png"
import laravel5 from "../../assests/images/laravel/laravel5.png"
import laravel50 from "../../assests/images/laravel/laravel50.png"
import laravel51 from "../../assests/images/laravel/laravel51.png"
import laravel52 from "../../assests/images/laravel/laravel52.png"
import laravel53 from "../../assests/images/laravel/laravel53.png"
import laravel54 from "../../assests/images/laravel/laravel54.png"
import laravel55 from "../../assests/images/laravel/laravel55.png"
import laravel57 from "../../assests/images/laravel/laravel57.png"
import laravel58 from "../../assests/images/laravel/laravel58.png"
import laravel59 from "../../assests/images/laravel/laravel59.png"
import laravel6 from "../../assests/images/laravel/laravel6.png"
import laravel60 from "../../assests/images/laravel/laravel60.png"
import laravel61 from "../../assests/images/laravel/laravel61.png"
import laravel62 from "../../assests/images/laravel/laravel62.png"
import laravel64 from "../../assests/images/laravel/laravel64.png"
import laravel65 from "../../assests/images/laravel/laravel65.png"
import laravel66 from "../../assests/images/laravel/laravel66.png"
import laravel67 from "../../assests/images/laravel/laravel67.png"
import laravel68 from "../../assests/images/laravel/laravel68.png"
import laravel7 from "../../assests/images/laravel/laravel7.png"
import laravel8 from "../../assests/images/laravel/laravel8.png"
import laravel9 from "../../assests/images/laravel/laravel9.png"

const images = {
    controller_r,index,Laravel0,laravel0_env,laravel0_env2,laravel0_env3,
    laravel0_layoute,laravel0_model1,laravel0_model2,laravel0_result,
    laravel0_result2,laravel0_show,laravel1,laravel10,laravel11,laravel12,
    laravel13,laravel14,laravel15,laravel16,laravel17,laravel18,laravel19,
    laravel2,laravel20,laravel21,laravel22,laravel23,laravel24,laravel25,
    laravel26,laravel27,laravel28,laravel29,laravel3,laravel30,laravel31,
    laravel32,laravel33,laravel34,laravel35,laravel36,laravel37,laravel38,
    laravel39,laravel4,laravel40,laravel41,laravel42,laravel43,laravel44,
    laravel45,laravel46,laravel47,laravel48,laravel49,laravel5,laravel50,
    laravel51,laravel52,laravel53,laravel54,laravel55,laravel57,laravel58,
    laravel59,laravel6,laravel60,laravel61,laravel62,laravel64,laravel65,
    laravel66,laravel67,laravel68,laravel7,laravel8,laravel9
}

export default images