import hajime from "../../assests/images/js/hajime.jpg"
import hajime2 from "../../assests/images/js/hajime2.jpg"
import js100_oncontextmenu from "../../assests/images/js/js100_oncontextmenu.png"
import js101_oncopy from "../../assests/images/js/js101_oncopy.png"
import js102_oncut from "../../assests/images/js/js102_oncut.png"
import js103_pageX from "../../assests/images/js/js103_pageX.png"
import js104_oninvalid from "../../assests/images/js/js104_oninvalid.png"
import js104_oninvalid2 from "../../assests/images/js/js104_oninvalid2.png"
import js105_onkeydown from "../../assests/images/js/js105_onkeydown.png"
import js106_onkeypress from "../../assests/images/js/js106_onkeypress.png"
import js107_onkeyup from "../../assests/images/js/js107_onkeyup.png"
import js108_onload from "../../assests/images/js/js108_onload.png"
import js109_onmousedown from "../../assests/images/js/js109_onmousedown.png"
import js110_onmouseup from "../../assests/images/js/js110_onmouseup.png"
import js111_onmouseenter from "../../assests/images/js/js111_onmouseenter.png"
import js112_onmouseleave from "../../assests/images/js/js112_onmouseleave.png"
import js113_onmousemove from "../../assests/images/js/js113_onmousemove.png"
import js114_event_target from "../../assests/images/js/js114_event_target.png"
import js114_event_target2 from "../../assests/images/js/js114_event_target2.png"
import js115_ondrag from "../../assests/images/js/js115_ondrag.png"
import js115_onmousemove from "../../assests/images/js/js115_onmousemove.png"
import js116_onsubmit from "../../assests/images/js/js116_onsubmit.png"
import js117_onended from "../../assests/images/js/js117_onended.png"
import js118_onfocusin from "../../assests/images/js/js118_onfocusin.png"
import js119_onerror from "../../assests/images/js/js119_onerror.png"
import js120_documentElement from "../../assests/images/js/js120_documentElement.png"
import js120_documentElement2 from "../../assests/images/js/js120_documentElement2.png"
import js121_exitFullscreen from "../../assests/images/js/js121_exitFullscreen.png"
import js122_onfullscreenchange from "../../assests/images/js/js122_onfullscreenchange.png"
import js123_onpagehide from "../../assests/images/js/js123_onpagehide.png"
import js124_onpaste from "../../assests/images/js/js124_onpaste.png"
import js125_onpause from "../../assests/images/js/js125_onpause.png"
import js126_onplay from "../../assests/images/js/js126_onplay.png"
import js127_onresize from "../../assests/images/js/js127_onresize.png"
import js128_onreset from "../../assests/images/js/js128_onreset.png"
import js128_onreset2 from "../../assests/images/js/js128_onreset2.png"
import js129_onscroll from "../../assests/images/js/js129_onscroll.png"
import js129_onscroll2 from "../../assests/images/js/js129_onscroll2.png"
import js130_onselect from "../../assests/images/js/js130_onselect.png"
import js131_ontoggle from "../../assests/images/js/js131_ontoggle.png"
import js132_onunload from "../../assests/images/js/js132_onunload.png"
import js133_ctrlKey from "../../assests/images/js/js133_ctrlKey.png"
import js134_onvolumechange from "../../assests/images/js/js134_onvolumechange.png"
import js134_onvolumechange2 from "../../assests/images/js/js134_onvolumechange2.png"
import js135_data from "../../assests/images/js/js135_data.png"
import js136_fetch from "../../assests/images/js/js136_fetch.png"
import js136_fetch2_2 from "../../assests/images/js/js136_fetch2 2.png"
import js136_fetch2 from "../../assests/images/js/js136_fetch2.png"
import js136_fetch3 from "../../assests/images/js/js136_fetch3.png"
import js136_fetch4 from "../../assests/images/js/js136_fetch4.png"
import js137_geolocation from "../../assests/images/js/js137_geolocation.png"
import js138_checkValidity from "../../assests/images/js/js138_checkValidity.png"
import js139_class_Intro from "../../assests/images/js/js139_class_Intro.png"
import js139_class_Intro2 from "../../assests/images/js/js139_class_Intro2.png"
import js139_class_Intro3 from "../../assests/images/js/js139_class_Intro3.png"
import js139_class_Intro4 from "../../assests/images/js/js139_class_Intro4.png"
import js140_class_static from "../../assests/images/js/js140_class_static.png"
import js140_class_static2 from "../../assests/images/js/js140_class_static2.png"
import js141_class_private from "../../assests/images/js/js141_class_private.png"
import js141_class_private2 from "../../assests/images/js/js141_class_private2.png"
import js142_class_Inheritance from "../../assests/images/js/js142_class_Inheritance.png"
import js142_class_Inheritance2 from "../../assests/images/js/js142_class_Inheritance2.png"
import js142_class_Inheritance3 from "../../assests/images/js/js142_class_Inheritance3.png"
import js143_map from "../../assests/images/js/js143_map.png"
import js143_map2 from "../../assests/images/js/js143_map2.png"
import js143_map3 from "../../assests/images/js/js143_map3.png"
import js144_filter from "../../assests/images/js/js144_filter.png"
import js144_filter2 from "../../assests/images/js/js144_filter2.png"
import js144_filter3 from "../../assests/images/js/js144_filter3.png"
import js145_remove from "../../assests/images/js/js145_remove.png"
import js145_remove2 from "../../assests/images/js/js145_remove2.png"
import js146_setAttribute from "../../assests/images/js/js146_setAttribute.png"
import js147_bind from "../../assests/images/js/js147_bind.png"
import js147_bind2 from "../../assests/images/js/js147_bind2.png"
import js147_bind3 from "../../assests/images/js/js147_bind3.png"
import js147_bind4 from "../../assests/images/js/js147_bind4.png"
import js147_bind5 from "../../assests/images/js/js147_bind5.png"
import js147_bind6 from "../../assests/images/js/js147_bind6.png"
import js148_currentTarget from "../../assests/images/js/js148_currentTarget.png"
import js149_call from "../../assests/images/js/js149_call.png"
import js149_call2 from "../../assests/images/js/js149_call2.png"
import js149_call3 from "../../assests/images/js/js149_call3.png"
import js150_apply from "../../assests/images/js/js150_apply.png"
import js150_apply2 from "../../assests/images/js/js150_apply2.png"
import js150_apply3 from "../../assests/images/js/js150_apply3.png"
import js150_apply4 from "../../assests/images/js/js150_apply4.png"
import js151_setTimeout from "../../assests/images/js/js151_setTimeout.png"
import js16_Switch from "../../assests/images/js/js16_Switch.png"
import js16_Switch2 from "../../assests/images/js/js16_Switch2.png"
import js16_Switch3 from "../../assests/images/js/js16_Switch3.png"
import js17_Arrays from "../../assests/images/js/js17_Arrays.png"
import js17_Arrays10 from "../../assests/images/js/js17_Arrays10.png"
import js17_Arrays11 from "../../assests/images/js/js17_Arrays11.png"
import js17_Arrays12 from "../../assests/images/js/js17_Arrays12.png"
import js17_Arrays13 from "../../assests/images/js/js17_Arrays13.png"
import js17_Arrays14 from "../../assests/images/js/js17_Arrays14.png"
import js17_Arrays15 from "../../assests/images/js/js17_Arrays15.png"
import js17_Arrays16 from "../../assests/images/js/js17_Arrays16.png"
import js17_Arrays17 from "../../assests/images/js/js17_Arrays17.png"
import js17_Arrays18 from "../../assests/images/js/js17_Arrays18.png"
import js17_Arrays19 from "../../assests/images/js/js17_Arrays19.png"
import js17_Arrays2 from "../../assests/images/js/js17_Arrays2.png"
import js17_Arrays20 from "../../assests/images/js/js17_Arrays20.png"
import js17_Arrays21 from "../../assests/images/js/js17_Arrays21.png"
import js17_Arrays3_2 from "../../assests/images/js/js17_Arrays3 2.png"
import js17_Arrays3 from "../../assests/images/js/js17_Arrays3.png"
import js17_Arrays4 from "../../assests/images/js/js17_Arrays4.png"
import js17_Arrays5 from "../../assests/images/js/js17_Arrays5.png"
import js17_Arrays6 from "../../assests/images/js/js17_Arrays6.png"
import js17_Arrays7 from "../../assests/images/js/js17_Arrays7.png"
import js17_Arrays8 from "../../assests/images/js/js17_Arrays8.png"
import js17_Arrays9 from "../../assests/images/js/js17_Arrays9.png"
import js18_Arrays from "../../assests/images/js/js18_Arrays.png"
import js18_Arrays10 from "../../assests/images/js/js18_Arrays10.png"
import js18_Arrays11 from "../../assests/images/js/js18_Arrays11.png"
import js18_Arrays12 from "../../assests/images/js/js18_Arrays12.png"
import js18_Arrays13 from "../../assests/images/js/js18_Arrays13.png"
import js18_Arrays14 from "../../assests/images/js/js18_Arrays14.png"
import js18_Arrays15 from "../../assests/images/js/js18_Arrays15.png"
import js18_Arrays16 from "../../assests/images/js/js18_Arrays16.png"
import js18_Arrays2 from "../../assests/images/js/js18_Arrays2.png"
import js18_Arrays3 from "../../assests/images/js/js18_Arrays3.png"
import js18_Arrays4 from "../../assests/images/js/js18_Arrays4.png"
import js18_Arrays5 from "../../assests/images/js/js18_Arrays5.png"
import js18_Arrays6 from "../../assests/images/js/js18_Arrays6.png"
import js18_Arrays7 from "../../assests/images/js/js18_Arrays7.png"
import js18_Arrays8 from "../../assests/images/js/js18_Arrays8.png"
import js18_Arrays9 from "../../assests/images/js/js18_Arrays9.png"
import js19_Loop from "../../assests/images/js/js19_Loop.png"
import js19_Loop10 from "../../assests/images/js/js19_Loop10.png"
import js19_Loop11 from "../../assests/images/js/js19_Loop11.png"
import js19_Loop2 from "../../assests/images/js/js19_Loop2.png"
import js19_Loop3 from "../../assests/images/js/js19_Loop3.png"
import js19_Loop4 from "../../assests/images/js/js19_Loop4.png"
import js19_Loop5 from "../../assests/images/js/js19_Loop5.png"
import js19_Loop6 from "../../assests/images/js/js19_Loop6.png"
import js19_Loop7 from "../../assests/images/js/js19_Loop7.png"
import js19_Loop8 from "../../assests/images/js/js19_Loop8.png"
import js19_Loop9 from "../../assests/images/js/js19_Loop9.png"
import js20_Object from "../../assests/images/js/js20_Object.png"
import js20_Object2 from "../../assests/images/js/js20_Object2.png"
import js20_Object3 from "../../assests/images/js/js20_Object3.png"
import js20_Object4 from "../../assests/images/js/js20_Object4.png"
import js20_Object5 from "../../assests/images/js/js20_Object5.png"
import js20_Object6 from "../../assests/images/js/js20_Object6.png"
import js21_Function from "../../assests/images/js/js21_Function.png"
import js21_Function2 from "../../assests/images/js/js21_Function2.png"
import js21_Function3 from "../../assests/images/js/js21_Function3.png"
import js21_Function4 from "../../assests/images/js/js21_Function4.png"
import js21_Function5 from "../../assests/images/js/js21_Function5.png"
import js21_Function6 from "../../assests/images/js/js21_Function6.png"
import js21_Function7 from "../../assests/images/js/js21_Function7.png"
import js21_Function8 from "../../assests/images/js/js21_Function8.png"
import js22_While from "../../assests/images/js/js22_While.png"
import js22_While2 from "../../assests/images/js/js22_While2.png"
import js22_While3 from "../../assests/images/js/js22_While3.png"
import js22_While4 from "../../assests/images/js/js22_While4.png"
import js22_While5 from "../../assests/images/js/js22_While5.png"
import js23_break from "../../assests/images/js/js23_break.png"
import js23_break2 from "../../assests/images/js/js23_break2.png"
import js24_Conversion from "../../assests/images/js/js24_Conversion.png"
import js24_Conversion2 from "../../assests/images/js/js24_Conversion2.png"
import js24_Conversion3 from "../../assests/images/js/js24_Conversion3.png"
import js24_Conversion4 from "../../assests/images/js/js24_Conversion4.png"
import js24_Conversion5 from "../../assests/images/js/js24_Conversion5.png"
import js24_Conversion6 from "../../assests/images/js/js24_Conversion6.png"
import js24_Conversion7 from "../../assests/images/js/js24_Conversion7.png"
import js24_Conversion8 from "../../assests/images/js/js24_Conversion8.png"
import js24_Conversion9 from "../../assests/images/js/js24_Conversion9.png"
import js25_Regular from "../../assests/images/js/js25_Regular.png"
import js25_Regular2 from "../../assests/images/js/js25_Regular2.png"
import js25_Regular3 from "../../assests/images/js/js25_Regular3.png"
import js25_Regular4 from "../../assests/images/js/js25_Regular4.png"
import js25_Regular5 from "../../assests/images/js/js25_Regular5.png"
import js26_Errors from "../../assests/images/js/js26_Errors.png"
import js26_Errors2 from "../../assests/images/js/js26_Errors2.png"
import js26_Errors3 from "../../assests/images/js/js26_Errors3.png"
import js26_Errors4 from "../../assests/images/js/js26_Errors4.png"
import js27_JSON from "../../assests/images/js/js27_JSON.png"
import js27_JSON2 from "../../assests/images/js/js27_JSON2.png"
import js27_JSON3 from "../../assests/images/js/js27_JSON3.png"
import js27_JSON4_2 from "../../assests/images/js/js27_JSON4 2.png"
import js27_JSON4 from "../../assests/images/js/js27_JSON4.png"
import js27_JSON5 from "../../assests/images/js/js27_JSON5.png"
import js27_JSON6 from "../../assests/images/js/js27_JSON6.png"
import js27_JSON7 from "../../assests/images/js/js27_JSON7.png"
import js28_Class from "../../assests/images/js/js28_Class.png"
import js29_alert from "../../assests/images/js/js29_alert.png"
import js30_confirm from "../../assests/images/js/js30_confirm.png"
import js31_prompt from "../../assests/images/js/js31_prompt.png"
import js32_btoa from "../../assests/images/js/js32_btoa.png"
import js32_btoa2 from "../../assests/images/js/js32_btoa2.png"
import js33_atob from "../../assests/images/js/js33_atob.png"
import js34_location from "../../assests/images/js/js34_location.png"
import js34_location2 from "../../assests/images/js/js34_location2.png"
import js34_location3 from "../../assests/images/js/js34_location3.png"
import js34_location4 from "../../assests/images/js/js34_location4.png"
import js34_location5 from "../../assests/images/js/js34_location5.png"
import js34_location6 from "../../assests/images/js/js34_location6.png"
import js34_location7 from "../../assests/images/js/js34_location7.png"
import js35_setInterval from "../../assests/images/js/js35_setInterval.png"
import js35_setInterval2 from "../../assests/images/js/js35_setInterval2.png"
import js36_clearInterval from "../../assests/images/js/js36_clearInterval.png"
import js37_frames from "../../assests/images/js/js37_frames.png"
import js37_frames2 from "../../assests/images/js/js37_frames2.png"
import js38_history from "../../assests/images/js/js38_history.png"
import js38_history2 from "../../assests/images/js/js38_history2.png"
import js38_history3 from "../../assests/images/js/js38_history3.png"
import js39_innerWidth from "../../assests/images/js/js39_innerWidth.png"
import js39_innerWidth2 from "../../assests/images/js/js39_innerWidth2.png"
import js40_clientWidth from "../../assests/images/js/js40_clientWidth.png"
import js40_clientWidth2 from "../../assests/images/js/js40_clientWidth2.png"
import js41_scrollBy from "../../assests/images/js/js41_scrollBy.png"
import js42_pageXOffset from "../../assests/images/js/js42_pageXOffset.png"
import js43_pageYOffset from "../../assests/images/js/js43_pageYOffset.png"
import js44_scrollIntoView from "../../assests/images/js/js44_scrollIntoView.png"
import js45_scrollTop from "../../assests/images/js/js45_scrollTop.png"
import js46_console from "../../assests/images/js/js46_console.png"
import js47_getComputedStyle from "../../assests/images/js/js47_getComputedStyle.png"
import js47_getComputedStyle2 from "../../assests/images/js/js47_getComputedStyle2.png"
import js47_getComputedStyle3 from "../../assests/images/js/js47_getComputedStyle3.png"
import js48_localStorage from "../../assests/images/js/js48_localStorage.png"
import js48_localStorage2 from "../../assests/images/js/js48_localStorage2.png"
import js49_sessionStorage from "../../assests/images/js/js49_sessionStorage.png"
import js49_sessionStorage2 from "../../assests/images/js/js49_sessionStorage2.png"
import js50_matchMedia from "../../assests/images/js/js50_matchMedia.png"
import js51_navigator from "../../assests/images/js/js51_navigator.png"
import js51_navigator2 from "../../assests/images/js/js51_navigator2.png"
import js51_navigator3 from "../../assests/images/js/js51_navigator3.png"
import js51_navigator4 from "../../assests/images/js/js51_navigator4.png"
import js51_navigator5 from "../../assests/images/js/js51_navigator5.png"
import js52_print from "../../assests/images/js/js52_print.png"
import js53_beforeprint_2 from "../../assests/images/js/js53_beforeprint 2.png"
import js53_beforeprint_3 from "../../assests/images/js/js53_beforeprint 3.png"
import js53_beforeprint from "../../assests/images/js/js53_beforeprint.png"
import js54_afterprint_2 from "../../assests/images/js/js54_afterprint 2.png"
import js54_afterprint_3 from "../../assests/images/js/js54_afterprint 3.png"
import js54_afterprint from "../../assests/images/js/js54_afterprint.png"
import js55_addEventListener from "../../assests/images/js/js55_addEventListener.png"
import js55_addEventListener2 from "../../assests/images/js/js55_addEventListener2.png"
import js55_addEventListener3 from "../../assests/images/js/js55_addEventListener3.png"
import js55_addEventListener4 from "../../assests/images/js/js55_addEventListener4.png"
import js55_addEventListener5 from "../../assests/images/js/js55_addEventListener5.png"
import js55_addEventListener6 from "../../assests/images/js/js55_addEventListener6.png"
import js55_addEventListener7 from "../../assests/images/js/js55_addEventListener7.png"
import js55_addEventListener8 from "../../assests/images/js/js55_addEventListener8.png"
import js56_removeEventListener from "../../assests/images/js/js56_removeEventListener.png"
import js57_activeElement from "../../assests/images/js/js57_activeElement.png"
import js57_activeElement2 from "../../assests/images/js/js57_activeElement2.png"
import js58_children from "../../assests/images/js/js58_children.png"
import js58_children2 from "../../assests/images/js/js58_children2.png"
import js59_baseURI from "../../assests/images/js/js59_baseURI.png"
import js60_body_2 from "../../assests/images/js/js60_body 2.png"
import js60_body from "../../assests/images/js/js60_body.png"
import js60_body2_2 from "../../assests/images/js/js60_body2 2.png"
import js60_body2 from "../../assests/images/js/js60_body2.png"
import js61_cookie from "../../assests/images/js/js61_cookie.png"
import js61_cookie2 from "../../assests/images/js/js61_cookie2.png"
import js62_classList from "../../assests/images/js/js62_classList.png"
import js62_classList2_2 from "../../assests/images/js/js62_classList2 2.png"
import js62_classList2 from "../../assests/images/js/js62_classList2.png"
import js62_classList3 from "../../assests/images/js/js62_classList3.png"
import js62_classList4 from "../../assests/images/js/js62_classList4.png"
import js62_classList5 from "../../assests/images/js/js62_classList5.png"
import js63_createAttribute from "../../assests/images/js/js63_createAttribute.png"
import js63_createAttribute2 from "../../assests/images/js/js63_createAttribute2.png"
import js64_createComment_2 from "../../assests/images/js/js64_createComment 2.png"
import js64_createComment from "../../assests/images/js/js64_createComment.png"
import js65_createElement from "../../assests/images/js/js65_createElement.png"
import js65_createElement2 from "../../assests/images/js/js65_createElement2.png"
import js65_createElement3 from "../../assests/images/js/js65_createElement3.png"
import js66_appendChild from "../../assests/images/js/js66_appendChild.png"
import js67_createTextNode from "../../assests/images/js/js67_createTextNode.png"
import js68_docktype from "../../assests/images/js/js68_docktype.png"
import js69_getElementById from "../../assests/images/js/js69_getElementById.png"
import js70_getElementsByClassName from "../../assests/images/js/js70_getElementsByClassName.png"
import js70_getElementsByClassName2 from "../../assests/images/js/js70_getElementsByClassName2.png"
import js71_getElementsByName from "../../assests/images/js/js71_getElementsByName.png"
import js71_getElementsByName2 from "../../assests/images/js/js71_getElementsByName2.png"
import js72_getElementsByTagName from "../../assests/images/js/js72_getElementsByTagName.png"
import js73_head from "../../assests/images/js/js73_head.png"
import js73_head2 from "../../assests/images/js/js73_head2.png"
import js74_images from "../../assests/images/js/js74_images.png"
import js75_links from "../../assests/images/js/js75_links.png"
import js76_querySelector from "../../assests/images/js/js76_querySelector.png"
import js76_querySelector2 from "../../assests/images/js/js76_querySelector2.png"
import js77_querySelectorAll from "../../assests/images/js/js77_querySelectorAll.png"
import js78_scripts from "../../assests/images/js/js78_scripts.png"
import js78_scripts2 from "../../assests/images/js/js78_scripts2.png"
import js79_title from "../../assests/images/js/js79_title.png"
import js79_title2 from "../../assests/images/js/js79_title2.png"
import js80_contains from "../../assests/images/js/js80_contains.png"
import js80_contains2 from "../../assests/images/js/js80_contains2.png"
import js80_contains3 from "../../assests/images/js/js80_contains3.png"
import js81_focus from "../../assests/images/js/js81_focus.png"
import js82_blur from "../../assests/images/js/js82_blur.png"
import js83_removeAttributre from "../../assests/images/js/js83_removeAttributre.png"
import js84_animation from "../../assests/images/js/js84_animation.png"
import js84_animation2 from "../../assests/images/js/js84_animation2.png"
import js84_animation3 from "../../assests/images/js/js84_animation3.png"
import js85_onfocus from "../../assests/images/js/js85_onfocus.png"
import js85_onfocus2 from "../../assests/images/js/js85_onfocus2.png"
import js86_onblur from "../../assests/images/js/js86_onblur.png"
import js87_play from "../../assests/images/js/js87_play.png"
import js88_pause from "../../assests/images/js/js88_pause.png"
import js89_load from "../../assests/images/js/js89_load.png"
import js90_onloadstart from "../../assests/images/js/js90_onloadstart.png"
import js91_ondurationchange from "../../assests/images/js/js91_ondurationchange.png"
import js92_onloadedmetadata from "../../assests/images/js/js92_onloadedmetadata.png"
import js93_onloadeddata from "../../assests/images/js/js93_onloadeddata.png"
import js94_onprogress from "../../assests/images/js/js94_onprogress.png"
import js95_oncanplay from "../../assests/images/js/js95_oncanplay.png"
import js96_onchange from "../../assests/images/js/js96_onchange.png"
import js96_onchange2 from "../../assests/images/js/js96_onchange2.png"
import js97_onclick from "../../assests/images/js/js97_onclick.png"
import js97_onclick2 from "../../assests/images/js/js97_onclick2.png"
import js98_ondblclick from "../../assests/images/js/js98_ondblclick.png"
import js99_oninput from "../../assests/images/js/js99_oninput.png"
import js_Introduction3 from "../../assests/images/js/js_Introduction3.png"
import music from "../../assests/images/js/music.mp3"
import video from "../../assests/images/js/video.mp4"
import html_logo from "../../assests/images/logo/html_logo.png"

const images = {  
    hajime,hajime2,js100_oncontextmenu,js101_oncopy,js102_oncut,js103_pageX,js104_oninvalid,
    js104_oninvalid2,js105_onkeydown,js106_onkeypress,js107_onkeyup,js108_onload,js109_onmousedown,
    js110_onmouseup,
    js111_onmouseenter,js112_onmouseleave,js113_onmousemove,js114_event_target,js114_event_target2,
    js115_ondrag,js115_onmousemove,js116_onsubmit,js117_onended,js118_onfocusin,js119_onerror,
    js120_documentElement,js120_documentElement2,js121_exitFullscreen,
    js122_onfullscreenchange,js123_onpagehide,js124_onpaste,js125_onpause,js126_onplay,
    js127_onresize,js128_onreset,js128_onreset2,js129_onscroll,js129_onscroll2,
    js130_onselect,js131_ontoggle,js132_onunload,js133_ctrlKey,js134_onvolumechange,
    js134_onvolumechange2,js135_data,js136_fetch,js136_fetch2_2,js136_fetch2,js136_fetch3,
    js136_fetch4,js137_geolocation,js138_checkValidity,js139_class_Intro,js139_class_Intro2,
    js139_class_Intro3,js139_class_Intro4,
    js140_class_static,js140_class_static2,js141_class_private,js141_class_private2,
    js142_class_Inheritance,js142_class_Inheritance2,js142_class_Inheritance3,js143_map,
    js143_map2,js143_map3,js144_filter,js144_filter2,js144_filter3,js145_remove,js145_remove2,
    js146_setAttribute,js147_bind,js147_bind2,js147_bind3,js147_bind4,js147_bind5,js147_bind6,
    js148_currentTarget,js149_call,js149_call2,js149_call3,
    js150_apply,js150_apply2,js150_apply3,js150_apply4,js151_setTimeout,js16_Switch,
    js16_Switch2,js16_Switch3,js17_Arrays,js17_Arrays10,js17_Arrays11,js17_Arrays12,js17_Arrays13,
    js17_Arrays14,js17_Arrays15,js17_Arrays16,js17_Arrays17,js17_Arrays18,js17_Arrays19,js17_Arrays2,
    js17_Arrays20,js17_Arrays21,js17_Arrays3_2,js17_Arrays3,js17_Arrays4,js17_Arrays5,js17_Arrays6,
    js17_Arrays7,js17_Arrays8,js17_Arrays9,js18_Arrays,js18_Arrays10,js18_Arrays11,js18_Arrays12,
    js18_Arrays13,js18_Arrays14,js18_Arrays15,js18_Arrays16,js18_Arrays2,js18_Arrays3,js18_Arrays4,
    js18_Arrays5,js18_Arrays6,js18_Arrays7,js18_Arrays8,js18_Arrays9,js19_Loop,js19_Loop10,js19_Loop11,
    js19_Loop2,js19_Loop3,js19_Loop4,js19_Loop5,js19_Loop6,js19_Loop7,js19_Loop8,js19_Loop9,js20_Object,
    js20_Object2,js20_Object3,js20_Object4,js20_Object5,js20_Object6,js21_Function,js21_Function2,
    js21_Function3,js21_Function4,js21_Function5,js21_Function6,js21_Function7,js21_Function8,
    js22_While,js22_While2,js22_While3,js22_While4,js22_While5,js23_break,js23_break2,js24_Conversion,
    js24_Conversion2,js24_Conversion3,js24_Conversion4,js24_Conversion5,js24_Conversion6,js24_Conversion7,
    js24_Conversion8,js24_Conversion9,js25_Regular,js25_Regular2,js25_Regular3,js25_Regular4,js25_Regular5,
    js26_Errors,js26_Errors2,js26_Errors3,js26_Errors4,js27_JSON,js27_JSON2,js27_JSON3,js27_JSON4_2,
    js27_JSON4,js27_JSON5,js27_JSON6,js27_JSON7,js28_Class,js29_alert,
    js30_confirm,js31_prompt,js32_btoa,js32_btoa2,
    js33_atob,js34_location,js34_location2,js34_location3,js34_location4,js34_location5,js34_location6,
    js34_location7,js35_setInterval,js35_setInterval2,js36_clearInterval,js37_frames,js37_frames2,
    js38_history,js38_history2,js38_history3,js39_innerWidth,js39_innerWidth2,
    js40_clientWidth,js40_clientWidth2,js41_scrollBy,js42_pageXOffset,
    js43_pageYOffset,js44_scrollIntoView,js45_scrollTop,js46_console,js47_getComputedStyle,
    js47_getComputedStyle2,js47_getComputedStyle3,js48_localStorage,js48_localStorage2,
    js49_sessionStorage,js49_sessionStorage2,js50_matchMedia,js51_navigator,
    js51_navigator2,js51_navigator3,js51_navigator4,js51_navigator5,js52_print,js53_beforeprint_2,
    js53_beforeprint_3,js53_beforeprint,js54_afterprint_2,js54_afterprint_3,js54_afterprint,
    js55_addEventListener,js55_addEventListener2,js55_addEventListener3,js55_addEventListener4,
    js55_addEventListener5,js55_addEventListener6,js55_addEventListener7,js55_addEventListener8,
    js56_removeEventListener,js57_activeElement,js57_activeElement2,js58_children,js58_children2,
    js59_baseURI,js60_body_2,js60_body,js60_body2_2,js60_body2,
    js61_cookie,js61_cookie2,js62_classList,js62_classList2_2,js62_classList2,js62_classList3,
    js62_classList4,js62_classList5,js63_createAttribute,js63_createAttribute2,js64_createComment_2,
    js64_createComment,js65_createElement,js65_createElement2,js65_createElement3,js66_appendChild,
    js67_createTextNode,js68_docktype,js69_getElementById,js70_getElementsByClassName,
    js70_getElementsByClassName2,js71_getElementsByName,js71_getElementsByName2,
    js72_getElementsByTagName,js73_head,js73_head2,js74_images,js75_links,js76_querySelector,
    js76_querySelector2,js77_querySelectorAll,js78_scripts,js78_scripts2,js79_title,js79_title2,
    js80_contains,js80_contains2,js80_contains3,js81_focus,js82_blur,js83_removeAttributre,
    js84_animation,js84_animation2,js84_animation3,js85_onfocus,js85_onfocus2,js86_onblur,
    js87_play,js88_pause,js89_load,js90_onloadstart,
    js91_ondurationchange,js92_onloadedmetadata,
    js93_onloadeddata,js94_onprogress,js95_oncanplay,js96_onchange,js96_onchange2,
    js97_onclick,js97_onclick2,js98_ondblclick,js99_oninput,
    
    
    js_Introduction3,music,video,html_logo,
 }
export default images ;