import {
    index2setting, index2includes_app_to_urlpatterns0 ,index2includes_app_to_urlpatterns1 ,
    index2templates0 , index2templates1 ,index2templates2, index2urls,index2views,index2models0,
    index2models1,index2admin,index2layout_file_to_avoid_repeat0,index2layout_file_to_avoid_repeat1,
    index2layout_file_to_avoid_repeat2,index2layout_file_to_avoid_repeat3,index3Parameter0,
    index3Parameter1,index3Parameter2,index3Parameter3,index3Parameter4,index3Parameter5,index3Relations0,
    index3Relations1,index3Relations2,index4manage_static_files0,index4manage_static_files1,
    index4manage_static_files2,index4manage_static_files3,index4manage_static_files4,
    index4Media_files0,index4Media_files1,index4Media_files2,index4Media_files3,index4Media_files4,
    index4Media_files5,index4Media_files6,index4Media_files7,index4Media_files8,
    index4Media_files9,index4Media_files10,index5Create_Public_templates0,index5Create_Public_templates1,
    index5Create_Public_templates2,index5template_filters0,index5template_filters1,
    index6list_display,index6prepopulated_fields,index6list_editable,index6inlines0,
    index6inlines1,index7get_absolute_url0,index7get_absolute_url1,index7get_absolute_url2,
    index7get_absolute_url3,index7get_absolute_url4,index7get_absolute_url5,index7get_absolute_url6,
    index7get_absolute_url7,index7get_absolute_url8,index7get_absolute_url9,index7get_absolute_url10,
    index7get_absolute_url11,index7get_absolute_url12,index7get_absolute_url13,index7annotate0,
    index7annotate1,index7annotate2,index7annotate3,index7annotate4,index7annotate5,index7annotate6,
    index7annotate7,index8include_urls_and_files_html0,index8include_urls_and_files_html1,
    index8include_urls_and_files_html2,index8include_urls_and_files_html3,index8include_urls_and_files_html4,
    index8include_urls_and_files_html5,index8include_urls_and_files_html6,index8include_urls_and_files_html7,
    index8include_urls_and_files_html8,index8include_urls_and_files_html9,index8include_urls_and_files_html10,
    index8Sign_Up0,index8Sign_Up1,index8Sign_Up2,index8Sign_Up3,index8Sign_Up4,index8Sign_Up5,
    index8Add_fields_to_User_SignUp0,index8Add_fields_to_User_SignUp1,index8Add_fields_to_User_SignUp2,
    index9send_email0,index9send_email1,index9send_email2,index9send_email3,index9send_email4,index9send_email5,
    index9list_emails0,index9list_emails1,index9list_emails2,index10Django_Pagination0,index10Django_Pagination1,
    index10Django_Pagination2, index10Django_Pagination3,index10Django_Pagination4,index10Django_Pagination5,
    index11Form0,index11Form1,index11Form2,index11Form3,index11Form4,index11Form5,
    
} from "./pathCodeDjango";
const codes = [
    {
        title:"Introduction", 
        What_is_Django:[],
        What_you_need_to_get_started:[],
        Verify_required_installations:[],
        Struct_Django:[],
    },
    {
        title:"virtualenv", 
        What_is_virtualenv:[],
        Install_virtualenv:[],
        Create_virtualenv:[],
        Activate_virtualenv:[],
        Deactivate_virtualenv:[],
        Check_packages_installed:[],
        Install_django:[],       
        Creating_Django_project:[],
        Get_version_installed_django:[],
        requirements:[],
        Running_development_server:[], 
    },
    {
        title:"First_Exemple", 
        Creation_app_in_project:[],
        settings:[index2setting()],
        includes_app_to_urlpatterns:[index2includes_app_to_urlpatterns0(),index2includes_app_to_urlpatterns1(),],
        templates:[index2templates0(),index2templates1(),index2templates2(),],
        urls:[index2urls()],
        views:[index2views()],
        models:[index2models0(),index2models1()],
        admin:[index2admin()],
        createsuperuser:[],
        layout_file_to_avoid_repeat:[index2layout_file_to_avoid_repeat0(),index2layout_file_to_avoid_repeat1(),index2layout_file_to_avoid_repeat2(),index2layout_file_to_avoid_repeat3()],
    },
    {
        title:"Model_Field_Reference",
        Definition:[],
        Fields:[],
        Relations:[index3Relations0(),index3Relations1(),index3Relations2(),],
        Parameter:[index3Parameter0(),index3Parameter1(),index3Parameter2(),index3Parameter3(),index3Parameter4(),index3Parameter5(),], 
    },
    {
        title:"Static_and_Media_files",
        Manage_static_files:[index4manage_static_files0(),index4manage_static_files1(),index4manage_static_files2(),index4manage_static_files3(),index4manage_static_files4()],
        Media_files:[index4Media_files0(),index4Media_files1(),index4Media_files2(),index4Media_files3(),index4Media_files4(),index4Media_files5(),index4Media_files6(),index4Media_files7(),index4Media_files8(),index4Media_files9(),index4Media_files10()],
    },
    {
        title:"about_templates",
        Create_Public_templates:[index5Create_Public_templates0(),index5Create_Public_templates1(),index5Create_Public_templates2()],
        templates_tags:[],
        csrf_token:[],
        template_filters:[index5template_filters0(),index5template_filters1()],
    },
    {
        title:"about_admin",
        list_display:[index6list_display()],
        prepopulated_fields:[index6prepopulated_fields()],
        list_editable:[index6list_editable()],
        inlines:[index6inlines0(),index6inlines1()],
    },
    {
        title:"about_models",
        get_absolute_url:[index7get_absolute_url0(),index7get_absolute_url1(),index7get_absolute_url2(),index7get_absolute_url3(),index7get_absolute_url4(),index7get_absolute_url5(),index7get_absolute_url6(),index7get_absolute_url7(),index7get_absolute_url8(),index7get_absolute_url9(),index7get_absolute_url10(),index7get_absolute_url11(),index7get_absolute_url12(),index7get_absolute_url13(),],
        create_a_database_backup:[],
        restore_the_data_from_the_backup:[],
        remove_all_from_db_models:[],
        annotate:[index7annotate0(),index7annotate1(),index7annotate2(),index7annotate3(),index7annotate4(),index7annotate5(),index7annotate6(),index7annotate7()],
    },
    {
        title:"User_Authentication",
        User_and_authontication:[],
        include_urls_and_files_html:[index8include_urls_and_files_html0(),index8include_urls_and_files_html1(),index8include_urls_and_files_html2(),index8include_urls_and_files_html3(),index8include_urls_and_files_html4(),index8include_urls_and_files_html5(),index8include_urls_and_files_html6(),index8include_urls_and_files_html7(),index8include_urls_and_files_html8(),index8include_urls_and_files_html9(),index8include_urls_and_files_html10(),],
        Sign_Up:[index8Sign_Up0(),index8Sign_Up1(),index8Sign_Up2(),index8Sign_Up3(),index8Sign_Up4(),index8Sign_Up5(),],
        Add_fields_to_User_SignUp:[index8Add_fields_to_User_SignUp0(),index8Add_fields_to_User_SignUp1(),index8Add_fields_to_User_SignUp2(),],
    },
    {
        title:"Django_Email",
        send_email:[index9send_email0(),index9send_email1(),index9send_email2(),index9send_email3(),index9send_email4(),index9send_email5(),],
        list_emails:[index9list_emails0(),index9list_emails1(),index9list_emails2(),],
    },
    {
        Django_Pagination:[index10Django_Pagination0(),index10Django_Pagination1(),index10Django_Pagination2(),index10Django_Pagination3(),index10Django_Pagination4(),index10Django_Pagination5(),],
    },
    {
        Form:[index11Form0(),index11Form1(),index11Form2(),index11Form3(),index11Form4(),index11Form5(),],
    },
    {
        ModelForm:[],
    },
    {
        title: "Django_Filter",
        models_Objecjs_filter:[],
        filter_from_dataBase_directly:[],
        filter_using_Q:[],
        lookup_expr:[],
    },
    {
        Exercice:[]
    },
    {
        Session:[]
    },
    {
        Context_Processors:[]
    },
    {
        How_Django_Work:[]
    },
    {
        title:"Ussing_Class_View",
        Push_data_from_urls_directly:[],
        use_basic_class:[],
        get_context_data:[],
        context_object_name:[],
        ordering:[],
        queryset:[],
        get_queryset:[],
    },
    {
        ngrok:[]
    },
    {
        End_project_in_DJANGO:[]
    },
]

export default codes;