import {
    index2setting, index2includes_app_to_urlpatterns0 ,index2includes_app_to_urlpatterns1 ,
    index2templates0 , index2templates1 ,index2templates2, index2urls,index2views,
} from "./pathCodeDjango";
const codes = [
    {
        title:"Introduction", 
        What_is_Django:[],
        What_you_need_to_get_started:[],
        Verify_required_installations:[],
        Struct_django:[],
    },
    {
        title:"virtualenv", 
        What_is_virtualenv:[],
        Install_virtualenv:[],
        Create_virtualenv:[],
        Activate_virtualenv:[],
        Deactivate_virtualenv:[],
        Check_packages_installed:[],
        Install_django:[],       
        Creating_Django_project:[],
        Get_version_installed_django:[],
        requirements:[],
        Running_development_server:[], 
    },
    {
        title:"First_Exemple", 
        Creation_app_in_project:[],
        settings:[index2setting()],
        includes_app_to_urlpatterns:[index2includes_app_to_urlpatterns0(),index2includes_app_to_urlpatterns1(),],
        templates:[index2templates0(),index2templates1(),index2templates2(),],
        urls:[index2urls()],
        views:[index2views()],
        models:[],
        Administering_data_in_Django:[],
        admin:[],
        create_file_to_avoid_repeat:[],
    },
    {
        title:"about_templates",
        templates_tags:[],
        csrf_token:[],
        as_p:[],
        load:[],
        template_filters:[],
        variable_date:[],
        variable_length:[],
    },
    {
        title:"about_admin",
        list_display:[],
        prepopulated_fields:[],
        list_filter:[],
        list_editable:[],
        inlines:[],
    },
    {
        title:"about_models",
        get_absolute_url:[],
        create_a_database_backup:[],
        restore_the_data_from_the_backup:[],
        remove_all_from_db_models:[],
        annotate:[],
    },
    {
        title:"Model_Field_Reference",
        function:[],
        param:[],
        Relations:[],
    },
    {
        title:"Static_files_Media_files",
        manage_static_files:[],
        Serving_files_uploaded_by_a_user_during_development:[],
    },
    {
        title:"user_authentication_without_Rest_framework",
        the_relation_between_class_User_and_authontication:[],
        include_urls_and_file_html:[],
        Sign_Up:[],
        Add_fields_to_User_SignUp:[],
        verificationEmailInSignUp:[],
        Add_Social_Login_to_Django:[],
    },
    {
        title:"using_email_in_django",
        send_email:[],
        list_emails:[],
        UseEmailAsUsername:[],
    },
    {
        django_Pagination:[],
    },
    {
        django_Slug:[]
    },
    {
        ModelForm:[],
    },
    {
        Form:[],
    },
    {
        title: "filterfromdataBase",
        models_Objecjs_filter:[],
        filter_from_dataBase_directly:[],
        filter_using_Q:[],
        lookup_expr:[],
    },
    {
        exercice:[]
    },
    {
        title:"Ussing_Class_View",
        Push_data_from_urls_directly:[],
        use_basic_class:[],
        get_context_data:[],
        context_object_name:[],
        ordering:[],
        queryset:[],
        get_queryset:[],
    },
    {
        SESSION:[]
    },
    {
        Context_Processors:[]
    },
    {
        How_Django_Work:[]
    },
    {
        ngrok:[]
    },
    {
        End_project_in_DJANGO:[]
    },
]

export default codes;